# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coursemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
                ('coursecode', models.CharField(max_length=40)),
                ('courseclass', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='studentmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=40)),
                ('emailaddress', models.EmailField(max_length=140)),
                ('enrolledcourses', models.ManyToManyField(to='assignment3.coursemodel')),
            ],
        ),
        migrations.CreateModel(
            name='teachermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=40)),
                ('odetails', models.CharField(max_length=140)),
                ('number', models.PositiveIntegerField(max_length=20)),
                ('emailaddress', models.EmailField(max_length=130)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment3.teachermodel'),
        ),
    ]
